---
title: "1 Num and 1 Cat Var Guided Lab 2025"
author: "Robert T Kohn"
date: "9/2/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

# Exploring the Data

```{r}
data(Births2015)
head(Births2015)
```

I predict that it is unlikely for a specific day to have the greatest amount of child births due to the randomness of labor. 


# Y and X Graphs

```{r}
require(ggforce)
gf_boxplot( births ~ wday , data = Births2015 , options,title="Boxplot")
gf_sina( births ~ wday , data = Births2015,title="Sina")
gf_jitter( births ~ wday , data = Births2015 ,title="jitter")
gf_violin( births ~ wday , data = Births2015 ,title="violin")
```


# \# vs X graphs

```{r}
gf_histogram(~births, data = Births2015,title="Histogram") %>%
gf_facet_wrap(~wday, ncol=1, strip.position = "right")
gf_density(~births, data = Births2015,title="Density") %>%
gf_facet_wrap(~wday, ncol=1, strip.position = "right")
gf_density( ~ births , data = Births2015 , fill = ~ wday , alpha = 0.5,title="NOT faceted, “filled")
gf_dens( ~ births , data = Births2015 , color = ~ wday , size = 2,title= "colored by day of the week")
library(ggridges)
gf_density_ridges(wday~births, data=Births2015, fill=~wday, show.legend = FALSE, scale = 2, alpha = 0.5,title="Density Ridges Plot") 
```



