---
title: "Color Guided Lab"
author: "Robert Thomas Kohn"
date: "9/22/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic( ))
```


# Start Graphing!

```{r}

gf_dist("chisq", df = 5)%>%gf_labs(x = "X", y = "Density", title="Showcasing Chi Squared Relationships" , subtitle = "" , caption = "df=5" )
gf_dist("chisq", df = 5)%>%gf_dist("chisq", df = 10)%>%gf_labs(x = "X", y = "Density", title="Showcasing Chi Squared Relationships" , subtitle = "" , caption = "df=5 and df=10" )
gf_dist("chisq", df = 5)%>%gf_dist("chisq", df = 10,color="orange")%>%gf_labs(x = "X", y = "Density", title="Showcasing Chi Squared Relationships" , subtitle = "df=5 is Black, df=10 is Orange" , caption = "df=5 and df=10" )
gf_dist("chisq", df = 5)%>%gf_dist("chisq", df = 10,color="orange")%>%gf_dist("chisq", df = 5,color="darkcyan",linetype="dashed")%>%gf_labs(x = "X", y = "Density", title="Showcasing Chi Squared Relationships" , subtitle = "df=5 is Black with Dark Cyan Dashes, df=10 is Orange" , caption = "2 df=5 and df=10" )#theme classic is default

#Alternative Option
gf_dist("chisq", df = 5, color = ~ "df = 5")%>%gf_dist("chisq", df = 10, color = ~ "df = 10")%>%gf_dist("chisq", df = 20, color = ~ "df = 20")%>%gf_labs(color = "DF")%>%gf_refine(scale_color_brewer(palette = "Paired"))


```

# Your Turn!! - Normal Distribution

```{r}

gf_dist("norm", mean = 0, sd = 1, color = ~ "mean = 0, sd = 1") %>% gf_dist("norm", mean = 0, sd = 2, color = ~ "mean = 0, sd = 2") %>% gf_dist("norm", mean = 0, sd = 3, color = ~ "mean = 0, sd = 3") %>% gf_labs(color = "Normal Distribution") %>% gf_refine(scale_color_brewer(palette = "Paired"))%>%gf_labs(x = "X", y = "Density", title="Normal Distribution Relationships as a Result of SD" , subtitle = "Cyan=1, Blue=2, Green=3" , caption = "R Colored Plot" )


gf_dist("norm", mean = 0, sd = 1,color="yellow")%>%gf_dist("norm", mean = 0, sd = 2,color="orange")%>%gf_dist("norm", mean = 0, sd = 3,color="red")%>%gf_labs(x = "X", y = "Density", title="Normal Distribution Relationships as a Result of SD" , subtitle = "Yellow=1SD, Orange=2SD, Red=3SD" , caption = "My Colored Plot" )
```


# Conditional Coloring

```{r}

require(MASS)
library(ggformula)
data(Cars93)
head(Cars93)
gf_point(MPG.highway ~ Weight , data = Cars93 )%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)" )
gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Price < 15) )%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)")
gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Price < 15) )%>%gf_refine(scale_color_manual(values = c("FALSE" = "blue", "TRUE" = "red"),labels = c("FALSE" = "Price More than $15,000", "TRUE" = "Price Less than $15,000")))%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)",color = "Price of Vehicle")
gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Price < 15) )%>%gf_refine(scale_color_manual(values = c("FALSE" = "blue", "TRUE" = "red"),labels = c("FALSE" = "Price More than $15,000", "TRUE" = "Price Less than $15,000")))%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)",color = "Price of Vehicle")%>%gf_theme( legend.position = c(0.7,0.7) )

```

# Color based on Categorical Condition

```{r}

gf_point(MPG.highway ~ Weight , data = Cars93 )%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)" )

gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Type=="Van") )%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)")

gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Type=="Van") )%>%gf_refine(scale_color_manual(values = c("FALSE" = "red", "TRUE" = "blue"),labels = c("FALSE" = "Is not a Van", "TRUE" = "Is a Van")))%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)",color = "Vehicle Type")%>%gf_theme( legend.position = c(0.7,0.7) )%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))#Everything after Gf_Labs is meta here

gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Type=="Van") )%>%gf_refine(scale_color_manual(values = c("FALSE" = "red", "TRUE" = "blue"),labels = c("FALSE" = "Is not a Van", "TRUE" = "Is a Van")))%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)",color = "Vehicle Type")%>%gf_theme( legend.position = c(0.7,0.7) )%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))%>%gf_text( 20 ~ 3500 , label = "Vans" , color = "deepskyblue3")

gf_point(MPG.highway ~ Weight , data = Cars93, color = ~(Type=="Van") ) %>%gf_refine(annotate(geom = "text", y = 20, x = 3500, label = "Vans", color = "deepskyblue3"),scale_color_manual(values = c("FALSE" = "red", "TRUE" = "blue"),labels = c("FALSE" = "Is not a Van", "TRUE" = "Is a Van")))%>%gf_labs(x = "X", y = "Density", title="The Heavier the Car, the Less MPG on the Highway" , subtitle = "Scatterplot of Weight vs MPG on the Highway" , caption = "Cars93(MASS)",color = "Vehicle Type")%>%gf_theme( legend.position = c(0.7,0.7) )%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
```


# Categorical Colors

```{r}

library(palmerpenguins)
data(penguins)
head(penguins)
require(viridis)

gf_density( ~ bill_length_mm , data = penguins , color = ~ species )%>%gf_labs(x = "Bill Length", y = "Density", title="Adeile have the Smallest Beaks Typically" , subtitle = "Density Plot of Bill Length per Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_density( ~ bill_length_mm , data = penguins , color = ~ species )%>%gf_refine( scale_fill_manual( values = c( "darkorange","purple","cyan4" ) ) )%>%gf_labs(x = "Bill Length", y = "Density", title="Adeile have the Smallest Beaks Typically" , subtitle = "Density Plot of Bill Length per Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_density( ~ bill_length_mm , data = penguins , color = ~ species )%>%gf_refine( scale_fill_brewer( palette = "Dark2" , limits = rev ) )%>%gf_labs(x = "Bill Length", y = "Density", title="Adeile have the Smallest Beaks Typically" , subtitle = "Density Plot of Bill Length per Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

gf_density( ~ bill_length_mm , data = penguins , color = ~ species )%>%gf_refine( scale_fill_viridis( discrete = TRUE, option = "magma", limits = rev ) )%>%gf_labs(x = "Bill Length", y = "Density", title="Adeile have the Smallest Beaks Typically" , subtitle = "Density Plot of Bill Length per Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

gf_histogram(~bill_length_mm, data = penguins, fill=~species, alpha = 0.5, position = position_identity())%>%gf_labs(x = "Bill Length", y = "Count", title="Adeile have the Smallest Beaks Typically" , subtitle = "Histogram of Bill Length per Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

```

# Highlight Using Discrete Color

```{r}

gf_point(flipper_length_mm ~ body_mass_g , data = penguins, color = ~(species))%>%gf_labs(x = "Mass(g)", y = "Flipper Length(mm)", title="Gentoo Penguins have the longest flippers" , subtitle = "Scatterplot of Weight vs Flipper Length when considering Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

gf_point(flipper_length_mm ~ body_mass_g , data = penguins,  color = ~species)%>%gf_facet_wrap(~species)%>%gf_labs(x = "Mass(g)", y = "Flipper Length(mm)", title="Gentoo Penguins have the longest flippers" , subtitle = "Scatterplot of Weight vs Flipper Length seperated by Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

gf_point(flipper_length_mm~body_mass_g, data=transform(penguins, species = NULL), color = "gray85", alpha = 0.4)%>%gf_point(flipper_length_mm ~ body_mass_g , data = penguins, color = ~(species))%>%gf_labs(x = "Mass(g)", y = "Flipper Length(mm)", title="Gentoo Penguins have the longest flippers" , subtitle = "Scatterplot of Weight vs Flipper Length when considering Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

gf_point(flipper_length_mm~body_mass_g, data=transform(penguins, species = NULL), color = "gray85", alpha = 0.4)%>%gf_point(flipper_length_mm ~ body_mass_g , data = penguins,  color = ~species)%>%gf_facet_wrap(~species)%>%gf_labs(x = "Mass(g)", y = "Flipper Length(mm)", title="Gentoo Penguins have the longest flippers" , subtitle = "Scatterplot of Weight vs Flipper Length seperated by Species" , caption = "Penguins(palmerpenguins)",color = "Species")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

```

# Continuous Color

```{r}

require(tidyr)
df.volcano = as.data.frame(volcano) %>%
mutate(X = seq(from = 1, to = 87, by=1)) %>%
pivot_longer(cols = starts_with("V"), names_to = "Y", names_prefix = "V", values_to = "Z") %>%
mutate(Y = as.numeric(Y))

gf_raster(Z~X+Y, data = df.volcano)%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void())%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void()) %>%gf_refine( scale_fill_gradient( low = "black", high = "purple" ) )%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void())%>%gf_refine(scale_fill_gradient2(low = "black", mid = "white", high = "purple"))%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void())%>%gf_refine(scale_fill_gradient2(low = "black", mid = "white", high = "purple", midpoint = 135))%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void())%>%gf_refine( scale_fill_distiller( palette = "BrBG" ) )%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_raster(Z~X+Y, data = df.volcano)%>%gf_theme(theme_void())%>%gf_refine( scale_fill_viridis( option = "magma" ) )%>%gf_labs(x = "x", y = "y", title="Volcano Plot" , subtitle = "" , caption = "df.volcano",color = "Z")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))


library(readr)
temps_months <- read_csv("https://wilkelab.org/SDS375/datasets/tempnormals.csv") %>%
group_by(location, month_name) %>%
summarize(mean = mean(temperature)) %>%
mutate(
month = factor(
month_name,
levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
"Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
),
location = factor(
location, levels = c("Death Valley", "Houston", "San Diego", "Chicago")
)
) %>%
dplyr::select(-month_name)
head(temps_months)

gf_tile( location ~ month , data = temps_months , fill = ~  mean)%>%gf_labs(x = "Month", y = "Location", title="Chicago is abnormally cool compared to other Major POIs" , subtitle = "" , caption = "temps_months(CSV)",color = "Mean Temperature")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_tile( location ~ month , data = temps_months , fill = ~  mean)%>% gf_refine(coord_fixed( ))%>%gf_labs(x = "Month", y = "Location", title="Chicago is abnormally cool compared to other Major POIs" , subtitle = "" , caption = "temps_months(CSV)",color = "Mean Temperature")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
gf_tile(location ~ month, data = temps_months, fill = ~mean) %>%gf_refine(coord_fixed(),scale_fill_gradient(low = "lightblue", high = "darkred")) %>%gf_labs(x = "Month", y = "Location", title="Chicago is abnormally cool compared to other Major POIs" , subtitle = "Dark Red is Hot, Light Blue is Cool" , caption = "temps_months(CSV)",color = "Mean Temperature")%>% gf_theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

```

Blue is known for being colder while red is more associated with heat.