---
title: "Consulting (Messy Data) Guided Lab"
author: "Robert Thomas Kohn"
date: "11/17/25"
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic( ))
library(dplyr)
library(stringr)
library(mosaic)
library(tidyverse)
```


# GERMINATING SEEDS DATA

```{r}

seeds = read.table("https://raw.githubusercontent.com/JedStephens/Handbook-of-Small-Data-Sets/master/GERMIN.DAT")


# Clean and reshape the data
seeds = seeds %>%
  mutate(V5 = parse_number(V5)) %>%
  rename(W1 = V1, W2 = V2, W3 = V3, W4 = V4, W5 = V5, W6 = V6) %>%
  mutate(Environment = c(rep("Uncovered", 4), rep("Covered", 4))) %>%
  pivot_longer(cols = starts_with("W"),
               names_to = "WaterLevel", 
               names_prefix = "W",
               values_to = "SeedsPer100")
head(seeds)

gf_point(SeedsPer100 ~ WaterLevel, data = seeds, color = ~Environment, alpha = 0.7) %>% gf_line(SeedsPer100 ~ WaterLevel, data = seeds, group = ~Environment, color = ~Environment, linetype = ~Environment) %>% gf_labs(title = "Seed Germination by Water Level and Environment", y = "Seeds Germinated per 100", x = "Water Level")

```

# Darwin Plant

```{r}
darwin = read.table("https://raw.githubusercontent.com/JedStephens/Handbook-of-Small-Data-Sets/master/DARWIN.DAT")
darwin = darwin %>%
  rename(Pair = V1, Cross = V2, Self = V3) %>%
  pivot_longer(cols = c(Cross, Self),
               names_to = "Fertilization",
               values_to = "Height")
head(darwin)
gf_boxplot(Height ~ Fertilization, data = darwin, fill = ~Fertilization, position = position_dodge(width = 0.75)) %>% gf_point(Height ~ Fertilization, data = darwin, position = position_jitter(width = 0.2), alpha = 0.6) %>% gf_labs(title = "Plant Heights by Fertilization Type", y = "Height (inches)", x = "Fertilization Method")


```