---
title: "Lab 1 - Integration"
author: "Robert T Kohn"
date: "9/9/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```


```{r}
myFunction=function(x){ x^2+3*x-4}
print(myFunction)
myFunction(0)
myFunction(1)
myFunction(100)
integrate(myFunction, 0,2)

#1st
whatthefunc=function(x){exp(3*x^2)*x^3}
integrate(whatthefunc, -0.5,1)

#2nd
funcmylife=function(x){((x^3)/(sin(x))^.5)}
integrate(funcmylife, 0,pi)

#3rd
funcoff=function(x){(exp((-1*x^2)/2)/(2*pi))}
integrate(funcoff, -1,1)

#4th
holyfunc=function(x){(exp((-1*x^2)/2)/(2*pi))}
integrate(holyfunc, -2,2)

#5h
funcingA=function(x){(exp((-1*x^2)/2)/(2*pi))}
integrate(funcingA, -3,3)
```
# Double Integration
```{r}
require(cubature)
myFunctionD=function(vec){ vec[1]^2+3*vec[1]*vec[2]-4*vec[2]^3}
print(myFunctionD)
adaptIntegrate(myFunctionD, c(0,1), c(2,1.5))

#1st
whatthefuncd=function(vec){ cos(vec[1])*(vec[2])^2}
adaptIntegrate(whatthefuncd, c(1,2), c(0,pi/2))

#2nd
funcmylifed=function(vec){exp(vec[1]^2)*2^(vec[2])}
adaptIntegrate(funcmylifed, c(0,.1), c(-2,2))

#3rd
funcoffd=function(vec){(2*pi)^-1*exp(-2^-1*(vec[1]^2+vec[2]))}
adaptIntegrate(funcoffd, c(-2,2), c(-2,2))

```