---
title: "Lab 3 - Discrete Monte Carlo"
author: "Robert Thomas Kohn"
date: "10/24/25"
output:
  pdf_document:
    latex_engine: lualatex
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic( ))
library(tidyverse)
library(mosaic)
```


# PART 1: DISCRETE DISTRIBUTION FUNCTIONS SECTION 

```{r}
set.seed(67) # after all why not
nb_values <- 0:5
nb_pdf <- dnbinom(nb_values, size = 3, prob = 0.8)
data.frame(x = nb_values, PDF = nb_pdf)#0-5 s=3 p=.8
qgeom(0.30, prob = 0.02)#30% of a geometric distribution with success probability 0.02
pbinom(8, size = 20, prob = 0.4)#P(X ≤ 8) for Binomial(20, 0.4)
pois_realizations <- rpois(50, lambda = 10)#50 realizations + 10 lambda
data.frame(Realization = pois_realizations) #50 Realizations

```

# PART 2: MONTE CARLO SIMULATION - THEORETICAL COMPARISON SECTION 

```{r}

#1
binom_sim <- rbinom(100000, size = 100, prob = 0.3)
var(binom_sim)#Monte Carlo Binomial variance
binom_var_theoretical <- 100 * 0.3 * (1 - 0.3)
binom_var_theoretical#Theoretical Binomial variance
var(binom_sim) - binom_var_theoretical #Difference

#2
x_sim <- rpois(100000, lambda = 2)
y_sim <- rgeom(100000, prob = 0.5)
sum_sim <- x_sim + y_sim
sum_mean_mc <- mean(sum_sim)
sum_mean_theoretical <- 2 + (1 - 0.5) / 0.5 #sum mean mathematically
sum_mean_mc#Monte Carlo E[X+Y]
sum_mean_theoretical#Theoretical E[X+Y]
sum_mean_mc - sum_mean_theoretical#Difference

#3
nb_sim <- rnbinom(100000, size = 5, prob = 0.65)#rand nb s=5 p=.65
p_gt_6_mc <- mean(nb_sim > 6)
p_gt_6_theoretical <- 1 - sum(sapply(0:6, function(k) { choose(k + 5 - 1, k) * (1 - .65)^k * .65^5})) #I was getting an error with summation so AI assisted with reformulating for NBD(Pascal) in Section 3.1b slides
p_gt_6_mc#Monte Carlo
p_gt_6_theoretical#Theoretical
p_gt_6_mc - p_gt_6_theoretical#Difference

```

# PART 3: COMPLEX MONTE CARLO SIMULATION SECTION 

```{r}

#1
humidity <- rbinom(100000, size = 5, prob = 0.3)#Cond 1
rain_prob <- humidity / 6 #Cond 2
will_rain <- rbinom(100000, size = 1, prob = rain_prob)#Cond 2(Rain is True)
sensors_working <- matrix(rbinom(100000 * 3, size = 1, prob = 0.7), ncol = 3)#Cond 3
detection <- will_rain * (rowSums(sensors_working) > 0)#Cond 3
rain_detector_sim <- data.frame(detection = detection)
mean(rain_detector_sim$detection)#Probability rain detector detects rain

#2
day_types <- rep(1:7, 20)  # 140 days
simulate_accidents <- function() {
  rain_days <- rbinom(140, 1, 0.25)#.25 rainy days in 140
  lambda_cars <- ifelse(day_types >= 6,ifelse(rain_days == 1, 50, 300),200)#1-5 weekday, 67 Weekend :)
  cars <- rpois(140, lambda_cars)#CPD
  accident_prob <- ifelse(rain_days == 1, 0.01, 0.001)#prob acc
  accidents <- rbinom(140, size = cars, prob = accident_prob) #apd
  sum(accidents)#ovr 140
}#fct form to simulate
accidents_total <- replicate(100000, simulate_accidents())
accidents_sim <- data.frame(total_accidents =accidents_total)
accidents_mean<-mean(accidents_sim$total_accidents)
accidents_sd<-sd(accidents_sim$total_accidents)
accidents_mean#mean
accidents_sd#sd
hist(accidents_sim$total_accidents, freq=F, main = "Histogram of Total Accidents with Normal Curve",xlab = "Total Accidents", ylab = "Density", col = "lightblue", border = "white")#hist w labels
lines(dnorm(0:200, mean=mean(accidents_sim$total_accidents), sd=sd(accidents_sim$total_accidents)), col="red")#normalized

```

