---
title: "Lab Chapter 4"
author: "Robert Thomas Kohn"
date: "11/6/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic())
library(tidyverse)
library(lubridate)
library(mosaic)
library(Lock5Data)
library(Stat2Data)
library(dplyr)
library(ggrepel)
library(scales)
library(stringr)
library(usmap)
library(mapdata)
library(maps)
library(mapdata)
library(tibble)
library(gapminder)
library(viridis)
library(usdata)
require(socviz)
library(statebins)
library(ggplot2)
```


# Part 1: Distribution Functions

```{r}

# 1. Generate a data frame consisting of 10 realizations from a Uniform distribution with lower limit 3 and upper limit 10.
uniform_realizations <- data.frame(Values = runif(10, min = 3, max = 10))
print(uniform_realizations)

# 2. Find the values of the probability density function for the integers 0 through 3 of an exponential distribution with rate parameter 2
dexp(0:3, 2)

# 3. Find the value that cuts off the bottom 70% of a chi squared distribution with 5 degrees of freedom
qchisq(0.70, 5)

# 4. Find P(X<=0.6) if X follows a Beta distribution with a=2 and b=4.
pbeta(0.6, 2, 4)

# 5. Generate a data frame consisting of 20 realizations from a Normal Random Variable with mean 50 and standard deviation 10.

normal_realizations <- data.frame(Values = rnorm(20, mean = 50, sd = 10))
print(normal_realizations)

```

# Part 2: Monte Carlo Approximations

```{r}


set.seed(41)
n <- 100000

# 1. The mean of X+Y if X~Uniform(0,3) and Y~Beta(a=3, b=1) and X and Y are independent
mean(runif(n, 0, 3) + rbeta(n, 3, 1)) #X+Y Mean
1.5 + 0.75 #Theory


# 2. The variance of W+ 2Z if W~chisq(df=7) Y~Normal(mean=0,sd=2) and W and Z are independent.
var(rchisq(n, 7) + 2 * rnorm(n, 0, 2))#W+2Z Variance: MC
14 + 16 #Theory

# 3. P(Q>0.3) if Q is Exponential with rate parameter 5.
mean(rexp(n, 5) > 0.3)#P(Q > 0.3)
1 - pexp(0.3, 5)#Theory


```


# Part 3: Complex Monte Carlo Simulations

```{r}

#Approximate the probability that a randomly selected person will score greater than a 90 on an Exam using the following criteria.

study_time <- rexp(n, rate = 1/2) # Exponential 
sleep_hours <- runif(n, 4, 9) # Uniform sleep
exam_mean <- 85 + 2 * study_time # Mean score
exam_sd <- sleep_hours / 10 # SD
exam_scores <- rnorm(n, exam_mean, exam_sd) # Scores
mean(exam_scores > 90)


#Approximate the probability distribution for the total distance that a bird will migrate(from starting location on day 0 to ending location on day 365) during 365 days using the following criteria. Present your result as a density plot in R using the code below, and approximate the mean and standard deviation of the probability distribution. Add a density curve to your plot that of a Normal Density with your approximate mean and variance.

result <- do(10000)*{
  rain <- rbinom(365, 1, 0.20)#rain
  wind <- rchisq(365, df = 3)#wind
  
  north_move <- ifelse(rain == 1,rnorm(365, 3, 2),rnorm(365, 10 + wind, 4)) # North dependency
  west_move <- ifelse(rain == 1, rnorm(365, 0, 1),rnorm(365, 1, 3)) # west depenedncy
  sqrt(sum(north_move)^2 + sum(west_move)^2)# Final distance
}

# Create histogram with density
hist(result$result, freq = FALSE, main = "Bird Migration Distance")
mean_dist <- mean(result$result)
sd_dist <- sd(result$result)
print(mean_dist)#mean
print(sd_dist)#sd
lines(2000:5000, dnorm(2000:5000, mean = mean_dist, sd = sd_dist), col = "red")#normal curve

```