---
title: "Map Guided Lab (Part 1)"
author: "Robert Thomas Kohn"
date: "10/27/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic( ))
library(tidyverse)
library(lubridate)
library(mosaic)
library(Lock5Data)
library(Stat2Data)
library(dplyr)
library(ggrepel)
library(scales)
library(stringr)
```


# Large Figures

```{r}
#Graph 1
require( maps )
require(mapproj)
states = map_data( "state" )
head( states )
gf_polygon( lat ~ long , data = states , group = ~ group )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )
theme_set(theme_map())
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )

#Graph 2
county = map_data( "county" )
head( county )
gf_polygon( lat ~ long , data = county , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )

#Graph 3

penn = map_data( "county" , "pennsylvania" )
head(penn)
gf_polygon( lat ~ long , data = penn , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )

```

# World Map Outline 

```{r}

#Graph 4

world = map_data("world")
head(world)
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.1 )
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine(coord_fixed())

#Graph 5

japan = map_data("world", "japan")
head(japan)
gf_polygon( lat ~ long , data = japan , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )


```


# Dot Overlay (Using Cities)


```{r}

data( "us.cities" )
head( us.cities )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , data = subset( us.cities, !( country.etc %in% c("AK", "HI" ) ) ) , alpha = 0.2 , group = NA )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , data = subset( us.cities, !( country.etc %in% c("AK", "HI" ) ) ) , alpha = 0.2 , group = NA, size = ~ pop )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , data = subset( us.cities, !( country.etc %in% c("AK", "HI" ) ) ) , alpha = 0.2 , group = NA, size = ~ pop/1000000)
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , data = subset( us.cities, !( country.etc %in% c("AK", "HI" ) ) ) , alpha = 0.2 , group = NA, size = ~ pop/1000000)%>% gf_labs( size = "Population\n(Millions)" )
gf_polygon( lat ~ long , data = states , group = ~ group , fill = NA , color = " black ", size = 0.5 )%>%gf_point( lat ~ long , data = subset( us.cities, !( country.etc %in% c("AK", "HI" ) ) ) , alpha = 0.2 , group = NA, size = ~ pop/1000000)%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in USA Cities")%>%gf_refine( coord_map("conic", lat0 = 30 ), scale_size( range = c( 0.01 , 24 ) ) )

#Graph 7

data(world.cities)
head(world.cities)
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.05 )%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in Global Cities") %>%gf_refine(coord_fixed(), scale_size( range = c( 0.01 , 24 ) ) )
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.05 )%>%gf_point( lat ~ long , data = world.cities , alpha = 0.1 , size = ~pop/1000000 , group = NA)%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in Global Cities") %>%gf_refine(coord_fixed(), scale_size( range = c( 0.01 , 24 ) ) )
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.05 )%>%gf_point( lat ~ long  , alpha = 0.1  , data = subset(world.cities, capital == 1), size = ~pop/1000000 , group = NA)%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in Global Cities") %>%gf_refine(coord_fixed(), scale_size( range = c( 0.01 , 24 ) ) )
gf_polygon( lat ~ long , data = world , group = ~ group , fill = NA , color = " black ", size = 0.05 )%>%gf_point( lat ~ long , alpha = 0.1  , data = subset(world.cities, capital == 1), size = ~pop/1000000 , group = NA)%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in Global Cities") %>%gf_refine(coord_fixed(), scale_size( range = c( 0.01 , 24 ) ) )%>% gf_theme(legend.position = "top")

#Graph 8
  
gf_polygon( lat ~ long , data = japan , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )
gf_polygon( lat ~ long , data = japan , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , alpha = 0.1  , data=subset(world.cities, country.etc == "Japan"), size = ~pop/1000000 , group = NA)
gf_polygon( lat ~ long , data = japan , group = ~ group , fill = NA , color = " black ", size = 0.1 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>%gf_point( lat ~ long , alpha = 0.1  , data=subset(world.cities, country.etc == "Japan" & capital == 1), color = "red", size = ~pop/1000000 , group = NA)

```

# Labels on All Cities within State


```{r}

# Graph 9 

ct = map_data( "county", "connecticut" )
gf_polygon( lat~long, data = ct, group = ~group, fill = NA, color = "black", size = 0.05 )
gf_polygon( lat ~ long , data = ct , group = ~ group , fill = NA , color = " black ", size = 0.05 )%>% gf_refine( coord_map( "conic" , lat0 = 30 ) )%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in Global Cities") 
head(us.cities)
gf_point( lat~long, data=subset( us.cities, country.etc == "CT"),alpha = 0.2, size = ~pop, show.legend = FALSE, group = NA)
#gf_polygon(lat ~ long, data = ct, group = ~group, fill = NA, color = "black", size = 0.05) + gf_point(lat ~ long, data = subset(us.cities, country.etc == "CT"), alpha = 0.2, size = ~pop, show.legend = FALSE) + gf_refine(coord_map("conic", lat0 = 30)) + gf_labs(size = "Population\n(Millions)", title = "Location and Pop Size in CT")
library(ggformula)
library(ggplot2)
ggplot() + geom_polygon(data = ct, aes(x = long, y = lat, group = group), fill = NA, color = "black", size = 0.05) + geom_point(data = subset(us.cities, country.etc == "CT"), aes(x = long, y = lat, size = pop), alpha = 0.2, show.legend = FALSE) + coord_map("conic", lat0 = 30) + labs(size = "Population\n(Millions)", title = "Location and Pop Size in CT") # This kept giving me and error so I had GPT revise it so it would run 
ggplot() + geom_polygon(data = ct, aes(x = long, y = lat, group = group), fill = NA, color = "black", size = 0.05) + geom_point(data = subset(us.cities, country.etc == "CT"), aes(x = long, y = lat, size = pop), alpha = 0.2, show.legend = FALSE) + coord_map("conic", lat0 = 30) + labs(size = "Population\n(Millions)", title = "Location and Pop Size in CT") + geom_text_repel( data = subset( us.cities , country.etc == "CT" ) ,aes( label = name , group = NA , x = long , y = lat ) ,size = 4 ,max.overlaps = 20 )
ggplot() + geom_polygon(data = ct, aes(x = long, y = lat, group = group), fill = NA, color = "black", size = 0.05) + geom_point(data = subset(us.cities, country.etc == "CT"), aes(x = long, y = lat, size = pop), alpha = 0.2, show.legend = FALSE) + coord_map("conic", lat0 = 30) + labs(size = "Population\n(Millions)", title = "Location and Pop Size in CT") + geom_text_repel( data = subset( us.cities , country.etc == "CT" ) ,aes( label = str_sub( name, end = -3 ) , group = NA , x = long , y = lat ) ,size = 4 ,max.overlaps = 20)

#Graph 10

ct = map_data( "county", "connecticut" )
gf_polygon( lat~long, data = ct, group = ~group, fill = NA, color = "black", size = 0.05 )
gf_polygon( lat~long, data = ct, group = ~group, fill = NA, color = "black", size = 0.05 )%>% gf_refine(coord_map( "conic" , lat0 = 30 ) )%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in CT Counties") 
gf_polygon( lat ~ long, data = ct , group = ~group,
fill = ~( subregion %in% c("tolland", "middlesex", "fairfield", "windham")),
color = "black", size = 0.05, show.legend = FALSE)%>% gf_refine(coord_map( "conic" , lat0 = 30 ) )%>% gf_labs( size = "Population\n(Millions)", title="Location and Pop Size in CT Counties") 

centroid.test = ct %>% # Note, you want to use your state dataset (I called mine penn)
group_by(group) %>% # Create averages for each county (group)
mutate(mean.lat = mean(lat), # Calculate the mean latitude & create a mean.lat variable
mean.long = mean(long)) %>% # Calculate the mean longitude & create a mean.long variable
dplyr::select(subregion, mean.lat, mean.long, group) %>% # Keep only these variables
unique() # Get rid of all the duplicate rows we now have

#centroid.test = ct %>% group_by(group) %>% mutate(mean.lat = mean(lat), mean.long = mean(long)) %>% dplyr::select(subregion, mean.lat, mean.long, group) %>%unique() %>%geom_label_repel(data = subset(centroid.test, subregion %in%c("tolland", "harford", "fairfield", "windham")),aes(x = mean.long, y = mean.lat, label = subregion), box.padding = 0.5, show.legend = FALSE, fill = "white") #error pt2

ggplot() + geom_polygon(data = ct, aes(x = long, y = lat, group = group),  fill = NA, color = "black", size = 0.05) + geom_point(data = subset(us.cities, country.etc == "CT"), aes(x = long, y = lat, size = pop), alpha = 0.2, show.legend = FALSE) + geom_label_repel(data = subset(centroid.test, subregion %in% c("tolland", "middlesex", "fairfield", "windham")), aes(x = mean.long, y = mean.lat, label = subregion),  box.padding = 0.5, show.legend = FALSE, fill = "white") + coord_map("conic", lat0 = 30) + labs(size = "Population\n(Millions)", title = "Location and Pop Size in CT") #GPT rewrote in ggplot2 again because of the unknown error with repel


```