---
title: "Maps Open Ended Assignment"
author: "Robert Thomas Kohn"
date: "11/6/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic())
library(tidyverse)
library(lubridate)
#library(mosaic)
library(Lock5Data)
library(Stat2Data)
library(dplyr)
library(ggrepel)
library(scales)
library(stringr)
library(usmap)
library(mapdata)
library(maps)
library(mapdata)
library(tibble)
library(gapminder)
library(viridis)
library(usdata)
require(socviz)
library(statebins)
library(ggplot2)
```


# Graph 1: US Map (labels)

```{r}
data(CollegeScores)
california_colleges <- CollegeScores %>% filter(State == "CA") %>% mutate(Name = str_to_title(Name))
california_map <- map_data("state", "california")
head(california_map)
#California Colleges
#gf_polygon(lat ~ long, data = california_map, group = ~group, fill = "lightblue", color = "black") %>% gf_point(Latitude ~ Longitude, data = california_colleges, size = ~Enrollment, color = ~Control, alpha = 0.7) %>% gf_refine(coord_map()) %>% gf_labs(title = "California has Coastal Colleges Primarily", subtitle="Sorted by Type and Enrollment", x = "Longitude", y = "Latitude")
ggplot() + geom_polygon(data = california_map, aes(x = long, y = lat, group = group),fill = "lightblue", color = "black") + geom_point(data = california_colleges, aes(x = Longitude, y = Latitude, size = Enrollment, color = Control), alpha = 0.7) + coord_map() + labs(title = "California has Coastal Colleges Primarily", subtitle="Sorted by Type and Enrollment", x = "Longitude", y = "Latitude") #ChatGPT fixed the never ending error I was getting in aestetics 

```


# Graph 2: World Map (dots)


```{r}

world <- map_data("world")
data(storms)
head(storms)

#Global Storms
#world %>% gf_polygon(lat ~ long, group = ~group, fill = "lightblue", color = "gray50") %>% gf_point(lat ~ long, data = storms, color = ~status, alpha = 0.6) %>% gf_refine(coord_quickmap()) %>% gf_labs(title = "The Worst Storms are in Central America", subtitle = "Global Storm Activity by Type", x = "Longitude", y = "Latitude", color = "Storm Type")

ggplot() +
  geom_polygon(data = world, aes(x = long, y = lat, group = group), 
               fill = "lightblue", color = "gray50") +
  geom_point(data = storms, aes(x = long, y = lat, color = status), alpha = 0.6) +
  coord_quickmap() +
  labs(title = "The Worst Storms are in Central America",
       subtitle = "Global Storm Activity by Type",
       x = "Longitude", y = "Latitude",
       color = "Storm Type") #ChatGPT fixed the never ending error I was getting in aestetics 

```

I'm going to go on a whim and assume something is wrong with the dataset as there is no storms besides in the Atlantic Ocean and neighboring areas. This is just false as there is currently typhoons/storms throughout Asia. 


# Graph 3: Any Map (Filled)

```{r}
data(world.cities)
head(world.cities)
country_pop <- world.cities %>% group_by(country.etc) %>% summarise(pop = sum(pop)) %>% mutate(region = country.etc)
world_pop_map <- right_join(country_pop, world, by = "region")
#World Pop by Country
gf_polygon(lat ~ long, data = world_pop_map, group = ~group, fill = ~pop, color = "gray50") %>% gf_refine(scale_fill_viridis_c(), coord_fixed()) %>% gf_labs(title="Asia is the Most Densely Populated",subtitle = "World Population by Country", fill = "Population")


```

