---
title: "Time Guided Lab"
author: "Robert Thomas Kohn"
date: "10/19/25"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
theme_set(theme_classic( ))
library(mosaic)
library(tidyr)
library(dplyr)
library(lubridate)
library(stevedata)
library(ggrepel)
library(mosaicData)
library(scales)
library(ggridges)
```

# Dow Jones 

```{r}
data(DJIA)
head(DJIA)

gf_line(value ~ date, data = DJIA) %>% gf_labs(title = "Dow Jones Industrial Average Over Time", x = "Year", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2000)) %>% gf_labs(title = "Dow Jones AVG Since 2000",x = "Year", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2000)) %>%gf_refine(scale_x_date(date_breaks = "2 years")) %>%gf_labs(title = "Dow Jones with 2-Year Breaks",x = "Year", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2000)) %>%gf_refine(scale_x_date(date_breaks = "2 years", date_labels = "%Y")) %>%gf_labs(title = "Dow Jones with Better Labels",x = "Year", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) == 2020)) %>%gf_refine(scale_x_date(date_breaks = "2 years", date_labels = "%Y")) %>%gf_labs(title = "Dow Jones COVID",x = "Year", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2020)) %>%
  gf_refine(scale_x_date(date_breaks = "1 month", date_labels = "%m")) %>%
  gf_labs(title = "Dow Jones COVID Monthly Breaks",x = "Month", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2020)) %>%
  gf_refine(scale_x_date(date_breaks = "1 month", date_labels = "%b")) %>%
  gf_labs(title = "Dow Jones COVID Monthly Breaks Abbr",x = "Month", y = "Dow Jones Value")
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2020)) %>% gf_refine(scale_x_date(date_breaks = "1 month", date_labels = "%b\n%Y")) %>%gf_labs(title = "Dow Jones Trends Since 2000",subtitle = "Monthly view with year labels",x = "Date", y = "Dow Jones Value")

#Final
gf_line(value ~ date, data = subset(DJIA, year(date) >= 2020)) %>%gf_refine(scale_x_date(date_breaks = "2 month", date_labels = "%b"))%>%gf_labs(title = "Dow Jones increased rapidly as COVID progessed",x = "Month", y = "Dow Jones Value", subtitle = "Bi-Monthly Dow Jones Value(2020)" , caption = "DIJA(stevedata)")%>%gf_theme(legend.position = "bottom",text = element_text(size = 8),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),axis.title.y = element_text(angle = 0, vjust = 0.5),plot.caption = element_text(size = 6)) # Revised Graph

```

# BIRTHS SECTION


```{r}
data(Births78)
head(Births78)
gf_line(births ~ date, data = Births78, color = ~wday) %>%gf_labs(title = "Daily Births by Day of Week",x = "Date", y = "Number of Births")
gf_line(births ~ date, data = Births78, color = ~wday) %>%gf_text(births ~ date, data = subset(Births78, date > as.Date("1978-12-24")), label = ~wday) %>% gf_labs(title = "Births with Day Labels",x = "Date", y = "Number of Births")
gf_line(births ~ date, data = Births78, color = ~wday) %>%gf_text(births ~ date, data = subset(Births78, date > as.Date("1978-12-24")), label = ~wday, hjust = -0.3) %>% gf_labs(title = "Births with , hjust = -0.3",x = "Date", y = "Number of Births")
gf_line(births ~ date, data = Births78, color = ~wday) %>%gf_text(births ~ date, data = subset(Births78, date >as.Date("1978-12-24")),label = ~wday, hjust = -0.3) %>%gf_theme(legend.position = "none") %>%gf_lims(x = c(as.Date("1978-01-01"), as.Date("1979-01-05"))) %>%gf_labs(title = "More Babies Born on Weekdays", x = "Date", y = "Number of Births")

#Final

gf_line(births ~ date, data = Births78, color = ~wday) %>% gf_text(births ~ date, data = subset(Births78, date >as.Date("1978-12-24")), label = ~wday, repel = TRUE, nudge_x = 15, segment.color = "gray60") %>%gf_theme(legend.position = "none") %>%gf_refine(coord_cartesian(xlim=c(as.Date("1978-01-01"), as.Date("1979-01-07"))))%>%gf_labs(title = "More Babies Born on Weekdays",x = "Date", y = "Number of Births", subtitle = "Birthrate by Weekday" , caption = "Births78(Lock5Data)")# Revised Graph

```

# CALENDAR VIEW SECTION

```{r}
gf_tile( strftime(date, format = "%V") ~ weekdays(date) , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)
gf_tile( strftime(date, format = "%V") ~ weekdays(date) , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)#%>%gf_refine( scale_y_reverse())
gf_tile( strftime(date, format = "%V") ~ weekdays(date) , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)%>% gf_theme( axis.text.y = element_blank( ) , axis.ticks.y = element_blank( ) )
gf_tile( strftime(date, format = "%V") ~ wday , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)%>% gf_theme( axis.text.y = element_blank( ) , axis.ticks.y = element_blank( ))
gf_tile( strftime(date, format = "%V") ~ wday , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)%>% gf_theme( axis.text.y = element_blank( ) , axis.ticks.y = element_blank( ))%>%gf_refine(scale_x_discrete(labels=function(x)abbreviate(x,minlength=1)))
gf_tile( strftime(date, format = "%V") ~ wday , data = Births78 , fill = ~births ) %>% gf_facet_wrap( ~ births)%>% gf_theme( axis.text.y = element_blank( ) , axis.ticks.y = element_blank( ))%>%gf_refine(scale_x_discrete(labels=function(x)abbreviate(x,minlength=1)))%>%gf_text( label = ~day(date), color = "white", size = 2)

Births_calendar <- Births78 %>% mutate(WeekOfMonth = ifelse(weekdays(date) == "Sunday",as.numeric(strftime(date, format = "%V")) + 1,as.numeric(strftime(date, format = "%V"))))


gf_tile(WeekOfMonth ~ wday, data = Births_calendar, fill = ~births) %>% gf_facet_wrap(~month(date, abbr = TRUE, label = TRUE))
gf_tile(WeekOfMonth ~ wday, data = Births_calendar, fill = ~births) %>% gf_facet_wrap(~month(date, abbr = TRUE, label = TRUE))%>%gf_refine(scale_y_reverse(),scale_x_discrete(labels = function(x) abbreviate(x, minlength = 1)),scale_fill_viridis_c(option = "plasma"))

gf_tile(WeekOfMonth ~ wday, data = Births_calendar, fill = ~births) %>%gf_facet_wrap(~month(date, abbr = TRUE, label = TRUE), scales = "free_y")%>%gf_refine(scale_y_reverse(),scale_x_discrete(labels = function(x) abbreviate(x, minlength = 1)),scale_fill_viridis_c(option = "plasma")) %>% gf_text(label = ~day(date), color = "white", size = 2) %>% gf_theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) %>% gf_labs(x = "", y = "", title = "Fewer Babies Born on Holidays & Weekends", subtitle = "Births Calendar View 1978")

```

# HUMIDITY BOXPLOTS SECTION

```{r}
data(Weather)
head(Weather)

gf_boxplot(avg_humidity ~ month(date), data = Weather)

WeatherWMonth <- Weather %>% mutate(Month = month(date, abbr = TRUE, label = TRUE))
gf_boxplot(avg_humidity ~ Month, data = WeatherWMonth) %>% gf_labs(title = "Humidity by Month Base", x = "Month", y = "Average Humidity (%)")
gf_boxplot(avg_humidity ~ Month, data = WeatherWMonth) %>% gf_facet_wrap(~city) %>% gf_theme(strip.text.y = element_text(angle = 0)) %>% gf_labs(title = "Humidity Patterns by City", x = "Month", y = "Average Humidity (%)")
gf_boxplot(avg_humidity ~ Month, data = WeatherWMonth) %>% gf_facet_wrap(~city, ncol = 1, strip.position = "right")%>% gf_labs(title = "Humidity Patterns by City and Month", x = "Month", y = "Average Humidity (%)")
gf_boxplot(avg_humidity ~ Month, data = WeatherWMonth) %>% gf_facet_wrap(~city, ncol = 1, strip.position = "right") %>% gf_theme(strip.text.y = element_text(angle = 0)) %>% gf_labs(title = "Humidity Patterns by City and Month", x = "Month", y = "Average Humidity (%)")

#Final

gf_boxplot(avg_humidity ~ Month, data = WeatherWMonth) %>% gf_facet_wrap(~city, ncol = 1, strip.position = "right") %>% gf_theme(strip.text.y = element_text(angle = 0)) %>% gf_labs(title = "Auckland is the most Humid City", caption = "Weather(mosaicData)",subtitle = "Humidity Patterns by City and Month", x = "Month", y = "Average Humidity (%)") #Revised
```

# HUMIDITY TILE GRAPH SECTION

```{r}

gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date), data = Weather, fill = ~avg_humidity)%>%gf_facet_wrap(~city)
gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date), data = Weather, fill = ~avg_humidity)%>%gf_facet_wrap(~city, nrow = 1)
gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date),  data = Weather, fill = ~avg_humidity) %>% gf_facet_wrap(~city, nrow = 1) %>% gf_refine(scale_y_discrete(limits = rev))

gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date), data = Weather, fill = ~avg_humidity) %>% gf_facet_wrap(~city, nrow = 1) %>% gf_refine(scale_y_discrete(limits = rev), scale_fill_distiller(palette = "RdBu", direction = 1))

gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date), data = Weather, fill = ~avg_humidity) %>% gf_facet_wrap(~city, nrow = 1) %>% gf_refine(scale_y_discrete(limits = rev), scale_fill_distiller(palette = "RdBu", direction = 1)) %>% gf_theme(legend.position = "bottom") 

#Final
gf_tile(month(date, abbr = TRUE, label = TRUE) ~ day(date), data = Weather, fill = ~avg_humidity) %>% gf_facet_wrap(~city, nrow = 1) %>% gf_refine(scale_y_discrete(limits = rev), scale_fill_distiller(palette = "RdBu", direction = 1)) %>% gf_theme(legend.position = "bottom") %>%gf_labs(x = "", y = "", fill = "Average Humidity", title = "Beijing has a Lower Humidity than other Cities", caption = "Weather(mosaicData)",subtitle = "Average Humidity Patterns by Day and Month") #Revised
```

# GRADIENT RIDGES SECTION

```{r}

BeijingWeather <- subset(Weather, city == "Beijing")

gf_density_ridges_gradient(month(date, abbr = TRUE, label = TRUE) ~ avg_humidity,data = BeijingWeather)

gf_density_ridges_gradient(month(date, abbr = TRUE, label = TRUE) ~ avg_humidity,data = BeijingWeather) %>% gf_refine(scale_y_discrete(limits = rev), scale_fill_distiller(palette = "RdBu", direction = 1)) %>% gf_theme(legend.position = "bottom")

gf_density_ridges_gradient(month(date, abbr = TRUE, label = TRUE) ~ avg_humidity,data = BeijingWeather) %>% gf_refine(scale_y_discrete(limits = rev), scale_fill_distiller(palette = "RdBu", direction = 1)) %>% gf_theme(legend.position = "bottom") %>%gf_theme(theme_ridges())

#final
gf_density_ridges_gradient(month(date, abbr = TRUE, label = TRUE) ~ avg_humidity,data = BeijingWeather) %>% gf_refine(scale_y_discrete(limits = rev),scale_fill_distiller(palette = "RdBu", direction = 1,breaks = c(20, 65, 95),labels = c("Drier", " ", "Stickler")))%>%gf_theme(theme_ridges()) %>%gf_labs(title = "Beijing Winters are Really Dry",x = "Average Relative Humidity", y = "Month", caption = "Weather(mosaicData)",subtitle = "Average Humidity Patterns by Day and Month in Beijing")

```

# PRECIPITATION AREA PLOT SECTION 

```{r}
gf_area(precip ~ date, data = Weather, fill = "deepskyblue") %>%gf_facet_wrap(~city)
gf_area(as.numeric(precip) ~ date, data = Weather, fill = "deepskyblue") %>%gf_facet_wrap(~city)
WeatherSubset <- subset(Weather, city != "Auckland" & year(date) == 2016)
WSC <- WeatherSubset %>%mutate(precip_numeric = ifelse(precip == "T", 0.001, as.numeric(precip)))

#Final
gf_area(precip_numeric ~ date, data = WSC, fill = "deepskyblue") %>%gf_facet_wrap(~city, ncol = 1, strip.position = "right", scales = "free_y") %>%gf_refine(scale_x_date(date_breaks = "2 months", date_labels = "%b\n%Y")) %>%gf_labs(title = "Chicago has precipitation all year round",subtitle = "Precipitation Patterns by City",x = "Date", y = "Precipitation (inches)", caption = "Weather(mosaicData)")

```

# TEMPERATURE LINERANGE PLOT SECTION

```{r}
gf_linerange(low_temp + high_temp ~ date, data = Weather, color = ~avg_temp) %>%gf_refine(scale_color_gradientn(colours = rev(rainbow(5)))) %>%gf_facet_grid(city ~ year, scales = "free_x")
gf_linerange(low_temp + high_temp ~ date, data = Weather, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),scale_x_date(date_breaks = "6 months", date_labels = "%b %Y")) %>%gf_labs(title="Chicago has Rapid Temperature Swings",subtitle = "Daily Temperature Ranges", x = "Date", y = "Temperature (°F)",color = "Average Temp", caption = "Weather(mosaicData)")

```

# TEMPERATURE RIBBON PLOT SECTION

```{r}

gf_ribbon( low_temp + high_temp ~ date , data = Weather)
gf_ribbon( low_temp + high_temp ~ date , data = Weather, fill=~city)
gf_ribbon( low_temp + high_temp ~ date , data = Weather, fill=~city)%>%gf_facet_wrap(~city)
gf_ribbon( low_temp + high_temp ~ date , data = Weather, fill=~city)%>%gf_facet_wrap(~city)%>%gf_refine(scale_x_date( date_breaks = "8 months", date_labels = "%b %y"))

#Final
gf_ribbon( low_temp + high_temp ~ date , data = Weather, fill=~city)%>%gf_facet_wrap(~city)%>%gf_refine(scale_x_date( date_breaks = "8 months", date_labels = "%b %y"))%>%gf_labs(title="Chicago and Beijing have Rapid Temperature Swings",subtitle = "Daily Temperature Ranges by City", x = "Date", y = "Temperature (°F)",color = "Average Temp", caption = "Weather(mosaicData)") #Revised

HighLow <- Weather %>% group_by(date) %>%mutate(lowest = min(low_temp),highest = max(high_temp))

gf_ribbon(lowest + highest ~ date, data = HighLow, fill = "gray85", alpha = 0.5) %>% gf_ribbon(low_temp + high_temp ~ date, data = Weather, fill = ~city, alpha = 0.8) %>% gf_facet_wrap(~city) %>% gf_theme(legend.position = "none") %>% gf_refine(scale_x_date(date_breaks = "8 months", date_labels = "%b %y")) %>%gf_labs(title="San Diego has the Most Average Temperature",subtitle = "Temperature Ranges by City",x = "Date", y = "Temperature (°F)",color = "Average Temp", caption = "Weather(mosaicData)")

```

# RADIAL TEMPERATURE PLOT SECTION

```{r}
Chicago2016 <- subset(Weather, city == "Chicago" & year(date) == 2016)

gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp)
gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar())
gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar(),scale_x_date(date_breaks = "1 month", date_labels = "%b"))
gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar(),scale_x_date(date_breaks = "1 month", date_labels = "%b"),scale_y_continuous(breaks = 0))
favstats(~avg_temp, data = Chicago2016)
gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar(),scale_x_date(date_breaks = "1 month", date_labels = "%b"),scale_y_continuous(breaks = 0))%>%gf_hline(yintercept = ~52.5, linetype = ~"Average (52)", color = "black") %>%gf_hline(yintercept = ~32, linetype = ~"Freezing (32)", color = "cyan2")
gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp) %>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar(),scale_linetype_manual(values = c("dashed", "dashed")),scale_x_date(date_breaks = "1 month", date_labels = "%b"),scale_y_continuous(breaks = 0))%>%gf_hline(yintercept = ~52.5, linetype = ~"Average (52)", color = "black") %>%gf_hline(yintercept = ~32, linetype = ~"Freezing (32)", color = "cyan2")

#Final
#gf_point(avg_temp ~ date, data = Chicago2016, color = ~avg_temp)%>%gf_labs(title="January is Chicago's Coldest Month",subtitle = "Chicago Temperatures 2016 - Radial View",x = "", y = "Temperature (°F)", caption = "Weather(mosaicData)")%>%gf_refine(scale_color_viridis_c(option = "turbo"),coord_polar(),scale_linetype_manual(values = c("dashed", "dashed")),scale_x_date(date_breaks = "1 month", date_labels = "%b"),scale_y_continuous(breaks = 0))%>%gf_hline(yintercept = ~52.5, linetype = ~"Average (52)", color = "black") %>%gf_hline(yintercept = ~32, linetype = ~"Freezing (32)", color = "cyan2")%>%scale_linetype_manual(values = c("dashed", "dashed")) #Revised


```

# CONNECTED SCATTERPLOT SECTION

```{r}

gf_path(high_temp ~ low_temp,data = subset(Weather, month == 5 & year == 2017 & city == "Chicago"),color = ~day) %>%gf_refine(scale_color_viridis_c(option = "C", begin = 0.2, end = 0.8)) %>%gf_labs(title = "Connected Scatterplot: High vs Low Temperatures",subtitle = "Chicago - May 2017",x = "Low Temperature (°F)",y = "High Temperature (°F)",caption = "Weather(mosaicData)" )


```

